webtalk_init -webtalk_dir E:/ISEN/VIVADO_stage_m1/PicoBlazeGIT01/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/Test_Bench2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep  5 16:10:26 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dbb1b929-ffc3-4a8f-9bbe-160b912b392e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "317cb4f24b3c417da9378d28afea8fd3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "33" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "465 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "56 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "604" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "314" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "285700_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3568336526 -regid "" -xml E:/ISEN/VIVADO_stage_m1/PicoBlazeGIT01/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/Test_Bench2_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/ISEN/VIVADO_stage_m1/PicoBlazeGIT01/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/Test_Bench2_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/ISEN/VIVADO_stage_m1/PicoBlazeGIT01/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/Test_Bench2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
